// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOtleBpBZAPQBQdzTTka8Wgof0Xauk5QQ',
    appId: '1:1064861195222:web:0daf14792f5f27ad21a277',
    messagingSenderId: '1064861195222',
    projectId: 'ewallet-2d1f1',
    authDomain: 'ewallet-2d1f1.firebaseapp.com',
    storageBucket: 'ewallet-2d1f1.firebasestorage.app',
    measurementId: 'G-RLE5KT51DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCupnof5EtOkIQVdFXOdLTtglgK1xjx95A',
    appId: '1:1064861195222:android:d3ab7e24db254fc621a277',
    messagingSenderId: '1064861195222',
    projectId: 'ewallet-2d1f1',
    storageBucket: 'ewallet-2d1f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx_7mejXOvdYRDGG8IPye1l3IvrFB8Rik',
    appId: '1:1064861195222:ios:e19a19ddab5334b521a277',
    messagingSenderId: '1064861195222',
    projectId: 'ewallet-2d1f1',
    storageBucket: 'ewallet-2d1f1.firebasestorage.app',
    iosBundleId: 'com.aniket.ewallet',
  );
}
